export { DeptApi } from './dept.api'
export { UserApi } from './user.api'
export { MenuApi } from './menu.api'
export { RoleApi } from './role.api'
export { JobApi } from './job.api'
export { DictDetailApi } from './dict-detail.api'
export { DictApi } from './dict.api'
export { LogsApi } from './logs.api'

export * from './user.type'
export * from './dict-detail.type'
export * from './job.type'
export * from './dept.type'
export * from './menu.type'
export * from './role.type'
export * from './dict.type'
export * from './logs.type'
