packages:
  - apis
  - common/**
  - components/**
  - apps/**
  - config/**
  - docs
catalog:
  "@antfu/eslint-config": ^4.10.1
  "@iconify/json": ^2.2.317
  "@iconify/tools": ^4.1.1
  "@iconify/utils": ^2.3.0
  "@rsbuild/core": ^1.2.19
  "@rsbuild/plugin-vue": ^1.0.7
  "@rsbuild/plugin-vue-jsx": ^1.1.0
  "@rslib/core": ^0.5.4
  "@shikijs/markdown-it": ^3.2.1
  "@types/fs-extra": ^11.0.4
  "@types/js-cookie": ^3.0.6
  "@types/lodash": ^4.17.16
  "@types/lodash-es": ^4.17.12
  "@types/markdown-it": ^14.1.2
  "@types/node": ^22.13.10
  "@types/three": ^0.174.0
  "@unocss/postcss": ^66.0.0
  "@unocss/preset-icons": ^66.0.0
  "@unocss/preset-uno": 66.1.0-beta.5
  "@unocss/reset": ^66.0.0
  "@unocss/transformer-directives": ^66.0.0
  "@unocss/webpack": 66.1.0-beta.5
  "@vitest/coverage-v8": ^3.0.8
  "@vitest/ui": ^3.0.8
  "@vue/compiler-core": ^3.5.13
  "@vue/tsconfig": ^0.7.0
  "@vueuse/core": ^13.0.0
  "@yy-web/request": ^1.5.9
  "@yy-web/use-curd-vue": ^1.0.1
  axios: ^1.8.3
  dayjs: ^1.11.13
  echarts: ^5.6.0
  eslint: ^9.22.0
  esno: ^4.8.0
  fs-extra: ^11.3.0
  js-cookie: ^3.0.5
  jsdom: ^26.0.0
  jsencrypt: ^3.3.2
  lodash-es: ^4.17.21
  markdown-it: ^14.1.0
  naive-ui: ^2.41.0
  pinia: ^3.0.1
  postcss-px-to-viewport: ^1.1.1
  rxjs: ^7.8.2
  shiki: ^3.2.1
  taze: ^19.0.2
  three: ^0.174.0
  turbo: ^2.4.4
  type-fest: ^4.37.0
  typescript: ^5.8.2
  unocss: ^66.0.0
  unplugin-auto-import: ^19.1.1
  unplugin-icons: ^22.1.0
  unplugin-vue-components: ^28.4.1
  unplugin-vue-markdown: ^28.3.1
  vant: ^4.9.18
  vitest: ^3.0.8
  vue: ^3.5.13
  vue-loader: ^17.4.2
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  vue-virtual-scroller: 2.0.0-beta.8
  webpack: ^5.98.0
