export { default as Login } from './components/login/index.vue'
export { default as Layout } from './components/layout/index.vue'
export { default as AppConfig } from './components/app-config/index.vue'
export * from './components/app-config/config'
export * from './components/dict'
export * from './bootstrap'
